### ISSUE TITLE
What is the corresponding 'format' value for native json?

### ISSUE THREAD

**Issue by firmianaQ** [tolgee/tolgee-cli#104]
JSON_TOLGEE is  Structured JSON 
What is the corresponding 'format' value for native json?

**Comment by stepan662** [comment]
Hey, what do you mean by native json?

**Comment by firmianaQ** [comment]
> 嘿，你说的原生json是什么意思？

[Tolgee Native JSON](https://tolgee.io/platform/formats/native_json)


Flatten JSON
```
{
  "user-settings.password.save.button": "Save",
  "interpolated_key": "Hello, {name}!",
  "plural_key": "You have {count, plural, one {one message} other {# messages}}."
}
```

**Comment by stepan662** [comment]
Ah, yeah the format is `JSON_TOLGEE` (the default one). You just need to set structure delimiter to empty string
```
tolgee pull --delimiter ""
```

That way it won't structure the json in any way.
