### ISSUE TITLE
Question: How to use TypeScript to write the custom extractor?

### ISSUE THREAD

**Issue by samislam** [tolgee/tolgee-cli#113]
This is the very simple and minimum extractor code:
```ts
module.exports = function extrator(code: string) {
  return {
    keys: [{ keyName: 'hi', line: 1 }],
    warnings: []
  }
}
```
And this is the .tolgeerc file
```
{
// ... etc
"extractor": "./src/config/tolgee/tolgee-extractor.ts"
}
```
When running any command on the CLI, I get this error:
```
┬─[~@~:~/D/p/s/~]─[10:18:18 PM]─[G:v1-dev>]
╰─>$ tolgee compare                                                                                                                                                                   22:18:18
🐭🔴     Analyzing code...
🔴 An unexpected error occurred while running the command.
🔴 Please report this to our issue tracker: https://github.com/tolgee/tolgee-cli/issues
🔴 Unknown file extension ".ts" for /~/src/config/tolgee/tolgee-extractor.ts
┬─[~@~:~/D/p/s/~]─[10:18:41 PM]─[G:v1-dev>]
╰─>$    
```
I read the documentation [here](https://tolgee.io/tolgee-cli/extraction/custom-extractor#using-your-custom-extractor), it's only written that in order to use TypeScript, just add `ts-node` to your project, I did that already:
```
$ pnpm add -D ts-node
```
But I am still getting the same error 🙁

**Comment by stepan662** [comment]
Hey, unfortunately it wasn't a reliable solution. I'll remove it from docs for now.

**Comment by samislam** [comment]
So for now we need to use .js, .mjs or .cjs files. And Typescript will not be supported. 
Or we'll transpile the extractor file (build it) and then use it in the cli.

**Comment by stepan662** [comment]
Yep, exactly. I'm sorry for confusion.
