### ISSUE TITLE
Regression with fast-glob and windows path

### ISSUE THREAD

**Issue by SeriousJul** [tolgee/tolgee-cli#120]
Hello team :)

There is a regression on windows regarding the cli `push` method combine with windows pathing.

This commit switch from `glob` to `fast-glob` [here](https://github.com/tolgee/tolgee-cli/commit/2e30591214dc8571ed24f08489c8c85e0ca56f6a) , unfortunately, `fast-glob` does not work with pattern that includes backward path separator [docs](https://github.com/mrmlnc/fast-glob?tab=readme-ov-file#how-to-write-patterns-on-windows)

Please note that I am using forward slash in my tolgee config. Unfortunately, it is being overriden by `resolve` [code](https://github.com/tolgee/tolgee-cli/blob/main/src/config/tolgeerc.ts#L59 )

**Comment by stepan662** [comment]
Hey, so switching back to regular glob would help you? Something like this?
https://github.com/tolgee/tolgee-cli/pull/121

**Comment by cyyynthia** [comment]
FWIW I did the change to reduce a bit the bundle size, although [tinyglobby](https://github.com/SuperchupuDev/tinyglobby) would be even better since it only has 2 dependencies compared to fast-glob's 17 deps

Vite uses this small helper to normalise slashes to posix-style forward slashes: https://github.com/vitejs/vite/blob/dbb260499f894d495bcff3dcdf5635d015a2f563/packages/vite/src/shared/utils.ts#L26-L29

**Comment by SeriousJul** [comment]
> Hey, so switching back to regular glob would help you? Something like this? #121

Yes it actually would, but reverting back to previous cli version is fine in the meantime too. We are clearly not blocked.

IMO the bundle size does not matter much, as it is not meant to be bundled with web app. But as pointed by @cyyynthia, if the bundle size matters and you want to move forward keeping fast-glob and normalize the path, another option is to leverage this vite helper function [docs](https://github.com/rollup/plugins/tree/master/packages/pluginutils#normalizepath) [code](https://github.com/rollup/plugins/blob/master/packages/pluginutils/src/normalizePath.ts)

**Comment by stepan662** [comment]
Ok, it's reverted
