### ISSUE TITLE
BUG: tolgee sync extract keys from tolgee-js test cases

### ISSUE THREAD

**Issue by paulwer** [tolgee/tolgee-cli#123]
Hi folks,
while using @tolgee/react and tolgee sync we realized, that translation keys (most likely from the test.spec files from tolgee-js) are included in the result, which is not the expected behavior.

![image](https://github.com/user-attachments/assets/eae10eee-2025-46e1-9cc4-3e5d438cb362)

F.ex. look at the peter_dogs key:
https://github.com/search?q=repo%3Atolgee%2Ftolgee-js%20peter_dogs&type=code

**Comment by JanCizmar** [comment]
@stepan662 can this be solved by updating the pattern?

**Comment by stepan662** [comment]
Yep, I guess you should be able to update the --patterns argument. We are using [glob](https://www.npmjs.com/package/glob) package to match files, so hopefully you should be able to match only what you want.

PS: better put the pattern into quotes (`--patterns '...'`), like this it won't collide with the terminal file matching.

**Comment by paulwer** [comment]
I think there should be a fix within tolgee-cli, because I cannot expect any use-case where the user would want to sync the translation keys from the package tolgee-js or any other package from node_modules.

My guess is, that this is from some test files, but i am not sure tbh.
I have not found the key peter_dogs anywhere in my repo and only within the files here:
https://github.com/search?q=repo%3Atolgee%2Ftolgee-js%20peter_dogs&type=code

**Comment by paulwer** [comment]
I also tried: tolgee sync src/shared/novu/email/** --parser react --patterns ./**/*.tsx
with the same result :)
I will do another check of any involved libs and will report back if i found something.

**Comment by paulwer** [comment]
I think I found the testfiles within the node_modules.
![image](https://github.com/user-attachments/assets/269e00c0-66a2-4f5a-a840-202a94f15b7a)

Maybe considder omiting these files in the npm build. 👍
I am using @tolgee/react@5.29.5

**Comment by cyyynthia** [comment]
Note that if these are discovered it means you have configured the CLI to traverse the entire project folder including the node_modules folder, which will make it process tons of useless files which is bad for performance. The patterns should be restricted to your own source files for faster processing

**Comment by paulwer** [comment]
Sorry for the inconveniance. How can I modify the following command, to only process the current folder?
`tolgee sync src/shared/novu/email/** --parser react --patterns ./**/*.tsx`

**Comment by stepan662** [comment]
Should be something like this.
`tolgee sync --parser react --patterns './src/**/*.tsx'`

The files right after sync command are not supported in since version 2.0

**Comment by paulwer** [comment]
Sorry, that was the missing piece for me. Thank you very much for yall support.
