### ISSUE TITLE
Add `--remove-unused` to `tolgee push`

### ISSUE THREAD

**Issue by cyyynthia** [tolgee/tolgee-cli#18]
Similar to what sync does, but except with files. Useful for people who don't use a SDK but still want to clean keys in bulk from the CLI

**Comment by nikolap** [comment]
Any chance this is still planned?

**Comment by JanCizmar** [comment]
Hello! 
It's a part of https://github.com/tolgee/tolgee-cli/issues/74

**Comment by cyyynthia** [comment]
Handled in #80 (`--remove-other-keys`)
