### ISSUE TITLE
The .tolgeerc should configure pattern

### ISSUE THREAD

**Issue by JanCizmar** [tolgee/tolgee-cli#28]
Currently I have to provide the pattern in every command. It has to be stored in the config:
```
 tolgee compare './src/**'
```

**Comment by cyyynthia** [comment]
The rationale for not implementing it right away and considering it a low-priority feature is the fact these scripts are likely to become scripts in the `package.json`. Standalone Prettier also works the same way, with scripts passed as params every time.

While it's a good QoL thing, I wouldn't consider it high priority

**Comment by cyyynthia** [comment]
Handled in #80
