### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'size')

### ISSUE THREAD

**Issue by WilliamMayor** [tolgee/tolgee-cli#33]
Hey, I don't think this is a duplicate of #30 but I might be wrong...

I'm running this command:

`npx tolgee --api-key "$PUBLIC_TOLGEE_API_KEY" compare '[GLOB]'`

And I see this error:

```
🐭✅     Analyzing code...
🔴 An unexpected error occurred while running the command.
🔴 Please report this to our issue tracker: https://github.com/tolgee/tolgee-cli/issues
TypeError: Cannot read properties of undefined (reading 'size')
    at compareKeys (/workdir/node_modules/@tolgee/cli/dist/commands/sync/syncUtils.js:52:30)
    at Command.compareHandler (/workdir/node_modules/@tolgee/cli/dist/commands/sync/compare.js:19:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.parseAsync (/workdir/node_modules/commander/lib/command.js:935:5)
    at async run (/workdir/node_modules/@tolgee/cli/dist/index.js:136:9)
```

I'm running this inside a docker image and I haven't installed the CLI tool globally (so I'm using `npx`).

Thanks!

**Comment by cyyynthia** [comment]
Does your project only contain namespaced keys? If so, then it is the same issue as #30

**Comment by WilliamMayor** [comment]
So I don't think it's a duplicate? I haven't set any namespaces, are the keys namespaced by default?

All my translations look like this: `{$t("about.title")}`

**Comment by WilliamMayor** [comment]
The title is all I have to go on really. When I try to run the command I get that traceback, I don't know enough about your code to know the true nature of the bug, sorry :(

**Comment by cyyynthia** [comment]
I meant of #30, not yours no worries :D

The stack trace looks the exact same of the one as the one fixed by #31; so I'm unsure if it is another bug, or the same bug. That being said, that `$t` is making me wonder: did you alias the `t` function? The CLI expects the naming schemes to be left intact (`useTranslate`, `t`, ...) and doesn't track renames. I believe this would trip the problematic code path and raise this error.

**Comment by WilliamMayor** [comment]
> I meant of https://github.com/tolgee/tolgee-cli/issues/30, not yours no worries :D
Oh I see!

I'm using SvelteKit and I think this is how I'm supposed to do it?

```
<script>
    import { getTranslate } from '@tolgee/svelte';
    const { t } = getTranslate();
</script>
<h1>{$t("about.title")}</h1>
```

**Comment by cyyynthia** [comment]
Ah, unfortunately the extraction for now only supports the React SDK (as documented [here](https://tolgee.io/tolgee-cli/extraction/syncing-strings)), so you won't be able to benefit from the code extraction yet.

**Comment by JanCizmar** [comment]
But... You can create the extractor for Svelte. PRs are welcomed! 🤩

**Comment by WilliamMayor** [comment]
Ah! Silly me! Should have RTFM :)

I'll investigate what would be needed for a SvelteKit extractor tomorrow. I'm also going to be looking at how to do server side generated pages (if you have any pointers?)

**Comment by cyyynthia** [comment]
> I'll investigate what would be needed for a SvelteKit extractor tomorrow.

The current state of the extractor is a bit of a pain to extend, if you have any questions on that (CLI internals, etc) that aren't answered by the [HACKING.md](https://github.com/tolgee/tolgee-cli/blob/main/HACKING.md), feel free to ping me on the [Tolgee community Slack](https://tolg.ee/slack) and I'll be able to help 👍🏻

**Comment by JanCizmar** [comment]
Hey, if you provide the static data before the page is generate / build, it works. You can check how it works in [Next.js](https://tolgee.io/js-sdk/integrations/react/ssr/next). Unfortunately, SvelteKit has no similar support for localized routing, which we are waiting for to update the docs properly.

You basically have to do it manualy. But it's possible. You can also ping **me** in Slack community. 😎
