### ISSUE TITLE
No API key has been provided error, even after successful login

### ISSUE THREAD

**Issue by ecstrema** [tolgee/tolgee-cli#35]
![image](https://user-images.githubusercontent.com/35939574/223774383-7b14c87b-c721-4c52-a376-cde549465472.png)

**Comment by ecstrema** [comment]
I tried resetting opening a new shell, resetting environmental variables, nothing seemed to work...

**Comment by cyyynthia** [comment]
When using a project API key with `toglee login`, you still need to specify a project ID when running commands.

The CLI can keep track of multiple project API keys and use the correct one based on the project you're working on, meaning it doesn't try whatever PAK it has in its store.

**Comment by ecstrema** [comment]
Oh of course. Does that mean I saved 3 or 4 times the same api key? Is there a way to list the saved api keys and the project they belong to?

**Comment by ecstrema** [comment]
Also, maybe that message could be clarified?

> NO API key has been provided. You must either provide one via --api -key, or login via tolgee login.

Maybe something like:

```
No API key has been provided. You must either provide one via --api-key, or login via tolgee login **and use --project-id** with the associated project id.
```

**Comment by ecstrema** [comment]
Finally, in a lot of cases (i.e. all of CI runs) there will only be one saved api-key via `tolgee login`. Would it be safe to automatically use the saved one if there is only one available?

```
No API key has been provided. You must either provide one via --api-key, or login via tolgee login **and use --project-id** with the associated project id.

You are only logged in for project "..." (id ...). Continuing in 3 seconds assuming you meant to use it. Press Ctrl+C to stop.
```

**Comment by cyyynthia** [comment]
> Oh of course. Does that mean I saved 3 or 4 times the same api key? Is there a way to list the saved api keys and the project they belong to?

If the key was for the same project every time, it overwrote the previous one. The CLI indexes keys by instance, type and project (for PAKs), overriding the already-existing one for this index if it already exists.

There's no list command key, but you can poke at the credentials store at `~/.config/tolgee/authentication.json`.

> Finally, in a lot of cases (i.e. all of CI runs) there will only be one saved api-key via tolgee login. Would it be safe to automatically use the saved one if there is only one available?

On CI, I'd strongly recommend using the `TOLGEE_API_KEY` environment variable (this recommendation is also documented [here](https://tolgee.io/tolgee-cli/usage#base-options)).

> Also, maybe that message could be clarified?

Probably, but your proposal doesn't work when the user logs in with a PAT: these tokens have access to all projects and the CLI will use it all the time when it exists. Also, in a project with a `.tolgeerc` configuration file, the project ID would automatically get looked up and the CLI would be able to route everything by itself automagically.

This case of "we do have a PAK stored, but the user didn't specify a project and there's no config file" could be identified, and the CLI could provide an additional hint. I think this case is globally not very well documented, so this would also be applicable for all the `help` messages and the documentation at tolgee.io

**Comment by ecstrema** [comment]
Ok, then I guess we could close this as by design?

**Comment by JanCizmar** [comment]
Can we maybe add better clear message? The error says "No API Key provided", but it's actually project id what's missing.

**Comment by paulwer** [comment]
May tolgee/cli could keep track of multiple keys and the cli could ask for which key should be used or if the user wants to initialise a new config?

**Comment by goors** [comment]
does not for me as well, like similar

`toglee login -ak keyhere -p id` give me error: missing required argument 'API Key'.
Only way that it works is if i just do `toglee login keyhere`

**Comment by stepan662** [comment]
Hey, `tolgee login <PAK | PAT>` is a correct way.

**Comment by JanCizmar** [comment]
```
toglee login -ak keyhere -p id
```
This syntax was never supported and hopefully not documented anywhere. Please let us know if you found it somewhere in our docs so we can fix it.
