### ISSUE TITLE
Feature Request: Add Vue2/Vue3 Extractor

### ISSUE THREAD

**Issue by paulwer** [tolgee/tolgee-cli#40]
Hey everyone,
I would like to see an vue3 extractor. Any plans?

Possible ressoruces:
https://www.npmjs.com/package/@xstate/vue
https://github.com/ChrisShank/xstate-vue2

**Comment by cyyynthia** [comment]
We definitely want to add support for extracting string for all the Tolgee SDKs, which does include `@tolgee/vue`. See #2 for the tracking issue.
