### ISSUE TITLE
Even though `delimiter` is set to `null`, sync command creates locales with nested keys.

### ISSUE THREAD

**Issue by baptisteArno** [tolgee/tolgee-cli#55]
`.tolgeerc`:

```ts
{
  "apiUrl": "<MY_API_URL>",
  "projectId": "1",
  "delimiter": null
}
```

command:

```sh
tolgee sync './apps/builder/src/**/*.ts?(x)' --continue-on-warning --remove-unused
```

It will create JSON files with nested keys. I'm expecting it to create flat keys.

**Comment by cyyynthia** [comment]
That's indeed a problem! You can work around this issue by using an empty string instead, it should yield the same result.

**Comment by baptisteArno** [comment]
Empty string does not seem to do the trick either!

**Comment by cyyynthia** [comment]
Hmm, that's problematic! I thought it'd do the trick but the way the config load is implemented is bogus and it won't work... Then the only remaining option to get around that is probably just to use the explicit CLI argument 😔

I will have a fix ready for it very soon!

**Comment by baptisteArno** [comment]
Got it! Thank you :)
