### ISSUE TITLE
Add existing keys values when syncing

### ISSUE THREAD

**Issue by baptisteArno** [tolgee/tolgee-cli#61]
Wouldn't it be nice when running `tolgee sync` to push the new strings with their existing values as well?

Currently, it will just push the new keys without translation values.

**Comment by cyyynthia** [comment]
If I understand correctly, this would be like a mix of the current sync (which only deals with source code and only pushes the default value if it found it) and push, where the sync command would peek values from the i18n/*.json files to push locally added translations in one go, right?

Something like (assuming there's a folder i18n with json files):
`tolgee sync --include-translations ./i18n 'src/**/*.ts?(x)'`

**Comment by baptisteArno** [comment]
Ok I just understood what exactly sync is doing then. The issue does not really make sense then.

I thought first that `sync` replaces the need to use `push` and `pull` but I was wrong :) It's just a way to extract the keys it can find in the code.
